import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Friend Phone!</h1>

        <p className={styles.description}>Join Russell's group by adding your phone number</p>
        <form onSubmit={(input) => console.log(input)} method='POST'>
          <label htmlFor='name'>Phone</label>
          <input id='name' type='text' autoComplete='phone' required />
          <button type='submit'>Join Group</button>
        </form>


        <p>Friend phone was made to help you stay connected with Russell. </p>
        <p>After you sign up - you will recieve occasional calls from Russell. </p>
        <p>Phone calls will come from 330-362-2448. If you are not free to talk do not answer.</p>




  

        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a href='https://pillar.gg' target='_blank' rel='noopener noreferrer'>
          Powered by
          <span className={styles.logo}>
            <Image
              src='https://pillar.gg/hubfs/pillarlogosvg.svg'
              alt='Pillar Logo'
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
